// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      print("flutterweb");
      return web;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for web - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyCnLb5QlOs1FR0DJq_8KnAv0o7vSV0JCrs',
    appId: '1:447841916444:android:bf4318465c59b3583fb1d9',
    messagingSenderId: '447841916444',
    projectId: 'pcs-mapp',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyCnLb5QlOs1FR0DJq_8KnAv0o7vSV0JCrs',
    appId: '1:269253835560:ios:6472e1c8d2e4f090e46e1d',
    messagingSenderId: '269253835560',
    projectId: 'pcs-mapp',
    iosBundleId: 'com.whizzstar.pcs', //'com.indyinvest.purse',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "",
    authDomain: "",
    projectId: "",
    storageBucket: "o",
    messagingSenderId: "",
    appId: "1:831524150145:web",
    measurementId: "G-",
  );
}
